# Generated by Django 5.1 on 2024-10-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_purchase', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price_selling', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
