# Generated by Django 5.1 on 2024-10-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_purchase',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_selling',
            new_name='selling_price',
        ),
    ]
